[versions]
version = "1.1.23"
group = "com.voinearadu"

[libraries]
# Testing
junit_jupiter = { module = "org.junit.jupiter:junit-jupiter ", version = "5.11.3" }
junit_bom = { module = "org.junit:junit-bom", version = "5.11.3" }

# Annotations
lombok = { module = "org.projectlombok:lombok", version = "1.18.36" }
jetbrains_annotations = { module = "org.jetbrains:annotations", version = "26.0.1" }

# Dependencies
gson = { module = "com.google.code.gson:gson", version = "2.11.0" }
jedis = { module = "redis.clients:jedis", version = "5.2.0" }
apache_commons_compress = { module = "org.apache.commons:commons-compress", version = "1.27.1" }
apache_commons_lang3 = { module = "org.apache.commons:commons-lang3", version = "3.17.0" }
apache_commons_pool2 = { module = "org.apache.commons:commons-pool2", version = "2.12.0" }
apache_commons_io = { module = "commons-io:commons-io", version = "2.17.0" }


