[versions]
version = "1.1.6"
group = "com.voinearadu"

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }

[libraries]
# Testing
junit_jupiter = { module = "org.junit.jupiter:junit-jupiter ", version = "5.11.0" }
junit_bom = { module = "org.junit:junit-bom", version = "5.11.0" }

# Annotations
lombok = { module = "org.projectlombok:lombok", version = "1.18.34" }
jetbrains_annotations = { module = "org.jetbrains:annotations", version = "24.1.0" }

# Dependencies
gson = { module = "com.google.code.gson:gson", version = "2.11.0" }
jedis = { module = "redis.clients:jedis", version = "5.1.5" }
apache_commons_compress = { module = "org.apache.commons:commons-compress", version = "1.27.1" }
apache_commons_lang3 = { module = "org.apache.commons:commons-lang3", version = "3.17.0" }
apache_commons_pool2 = { module = "org.apache.commons:commons-pool2", version = "2.12.0" }
apache_commons_io = { module = "commons-io:commons-io", version = "2.16.1" }
slf4j = { module = "org.slf4j:slf4j-api", version = "2.0.16" }
slf4j_log4j = { module = "org.slf4j:slf4j-log4j12", version = "2.0.16" }
log4j = { module = "org.apache.logging.log4j:log4j-core", version = "2.24.0" }


